name: ğŸ”— GHA
on: [push, pull_request, merge_group]

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-runner
  cancel-in-progress: true

jobs:
  dispatch:
    name: ğŸ Dispatch
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      android: ${{ steps.filter_macos.outputs.android }}
      ios: ${{ steps.filter_macos.outputs.ios }}
      linux: ${{ steps.filter_macos.outputs.linux }}
      macos: ${{ steps.filter_macos.outputs.macos }}
      windows: ${{ steps.filter_macos.outputs.windows }}
      web: ${{ steps.filter_macos.outputs.web }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: AurorNZ/paths-filter@298e00d16954592b06fe237dbf749947c3dd4a98
      id: filter_macos
      with:
        base: linux-change
        filters: |
          android:
            - '**'
            - '!platform/*/**'
            - 'platform/android/**'
          ios:
            - '**'
            - '!platform/*/**'
            - 'platform/ios/**'
          linux:
            - '**'
            - '!platform/*/**'
            - 'platform/linuxbsd/**'
          macos:
            - '**'
            - '!platform/*/**'
            - 'platform/macos/**'
          windows:
            - '**'
            - '!platform/*/**'
            - 'platform/windows/**'
          web:
            - '**'
            - '!platform/*/**'
            - 'platform/web/**'

  # First stage: Only static checks, fast and prevent expensive builds from running.

  static-checks:
    if: '!vars.DISABLE_GODOT_CI'
    name: ğŸ“Š Static checks
    uses: ./.github/workflows/static_checks.yml

  # Second stage: Run all the builds and some of the tests.

  android-build:
    name: ğŸ¤– Android
    needs: [static-checks, dispatch]
    if: needs.dispatch.outputs.android == 'true'
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: ğŸ iOS
    needs: [static-checks, dispatch]
    if: needs.dispatch.outputs.ios == 'true'
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: ğŸ§ Linux
    needs: [static-checks, dispatch]
    if: needs.dispatch.outputs.linux == 'true'
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: ğŸ macOS
    needs: [static-checks, dispatch]
    if: needs.dispatch.outputs.macos == 'true'
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: ğŸ Windows
    needs: [static-checks, dispatch]
    if: needs.dispatch.outputs.windows == 'true'
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: ğŸŒ Web
    needs: [static-checks, dispatch]
    if: needs.dispatch.outputs.web == 'true'
    uses: ./.github/workflows/web_builds.yml

  # Third stage: Run auxiliary tests using build artifacts from previous jobs.

  # Can be turned off for PRs that intentionally break compat with godot-cpp,
  # until both the upstream PR and the matching godot-cpp changes are merged.
  godot-cpp-test:
    name: ğŸª² Godot CPP
    # This can be changed to depend on another platform, if we decide to use it for
    # godot-cpp instead. Make sure to move the .github/actions/godot-api-dump step
    # appropriately.
    needs: linux-build
    uses: ./.github/workflows/godot_cpp_test.yml
